spring:
  cloud:
    aws:
      region:
        static: ap-southeast-2
      credentials:
        accessKey: ${AWS_ACCESS_KEY}  # Use environment variables instead
        secretKey: ${AWS_SECRET_KEY}
  main:
    lazy-initialization: false

myapp:
  queue:
    name: my-springboot-queue
server:
  port: 8083